### ISSUE TITLE
unable to connect to https://defense-eu.conferdeploy.net

### ISSUE THREAD

**Issue by mohammedha** [carbonblack/carbon-cli#44]
**Describe the bug**

**To Reproduce**
- open pwsh [powershell 7]
- Connect-CbcServer -Uri https://defense-eu.conferdeploy.net -Org xxxxxxxxxx -Token xxxxxxxxxxxxxxxxxxxxxxxxx -SaveConnection
I get the following error

```
ErrorRecord                 : Cannot connect to the server
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot connect to the server
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

**Expected behavior**
Connect successfully, I am able to connect with the same ID, ORG and Token using Postman
<img width="1329" alt="2024-09-17_14h17_12" src="https://github.com/user-attachments/assets/d9eeb478-ff64-4f21-ac5b-2cb3137c3a03">

**Screenshots**
If applicable,
<img width="1318" alt="2024-09-17_14h14_01" src="https://github.com/user-attachments/assets/e7cb6980-1bc1-4a4e-b64c-f9dd6a357fa9">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 128.0.2739.67

**Additional context**
I am able to connect via postman using the same API key

**Comment by emitreva-cb** [comment]
It should be fixed, can you please pull the latest changes and retest? Carbon cli was adding additional `/` at the end, which caused this error, if you test via Postman with extra `/` you are going to see the error too.

**Comment by mohammedha** [comment]
Thank you.

**Comment by emitreva-cb** [comment]
@mohammedha, can we close this issue if is working now?
